### PR TITLE
Modified incremental safe check which does not depend on snapshots list order

### LINKED ISSUE #660: XTable is doing a full sync instead of incremental sync in certain cases
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

I am using Iceberg tables and converting into Delta using XTable. Below is the behavior I noticed.

- If I do conversion after every Iceberg commit, XTable is doing incremental sync
- If I do conversion after >=2 Iceberg commits, then XTable is doing full sync and seeing below log info:
             **"Incremental sync is not safe from instant {}. Falling back to snapshot sync."**
- In Iceberg snapshots I see multiple snapshot's timestamp <= last instant sync timestamp from latest Delta log

### Are you willing to submit PR?

- [x] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by brishi19791**
Fixes #660

### CODE REVIEW

**Comment by the-other-tim-brown** [comment]
@brishi19791 can you run `mvn spotless:apply` to fix the style issues?

**Comment by brishi19791** [comment]
@the-other-tim-brown I have added the test changes from PR #663. let me know if I missed anything.

File: xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java [hunk 1]
```diff
@@ -246,31 +246,23 @@ public CommitsBacklog<Snapshot> getCommitsBacklog(InstantsForIncrementalSync las
...
-    // nothing has to be null in this chain to guarantee safety of incremental sync.
-    Long currentSnapshotId = iceTable.currentSnapshot().snapshotId();
-    while (currentSnapshotId != null && currentSnapshotId != targetSnapshotId) {
-      Snapshot currentSnapshot = iceTable.snapshot(currentSnapshotId);
-      if (currentSnapshot == null) {
-        // The snapshot is expired.
+
+      Snapshot parentSnapshot = iceTable.snapshot(parentSnapshotId);
+      if (parentSnapshot == null) {
+        // chain is broken due to expired snapshot
```
Comment (ashvina) [inline xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java:260]: @brishi19791 thanks for the PR.
Would it be helpful in debugging if we log the expired snapshot id, i.e. whenever safe icremental sync is `false`.

**Review by ashvina — APPROVED** [review]
LGTM 👍 
One minor suggestion

File: xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java (hunk 1 above)
Comment (brishi19791) [reply xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java:260]: @ashvina yes, it would be helpful for debugging. done

**Review by the-other-tim-brown — APPROVED** [review]
Thanks for the fix! Can you squash down to 1 commit? Then we can merge it for you.
